ABOUT: i'm deeply passionate about data engineering,analytics,and distributed systems.
.designing ETL pipelines
.managing data lakes and warehouse
.Building AWS-based architectures
EXPERIENCES: Data Analyst Intern – Futurense Technologies
.Built scalable ETL pipelines
.Automated AWS Lambda workflows
.Created Tableau & QuickSight dashboards

SKILLS: Languages & Tools:Python, SQL, PostgreSQL, Scala, AWS, Tableau, Power BI, Spark, Hadoop, Apache Ignite, NoSQL
Core Skills: ETL Development, Big Data Pipelines, Data Warehousing, Visualization
Soft Skills: Leadership, Teamwork, Communication, Time Management 
PROJECTS :
EDUCATION :M.S. in Computer Science – University of South Dakota
B.Tech in CSE: bharath institute of higher education and research
Graduate Seminar: Presented on xAI’s Grok 3 & Super Grok – DeepSearch, STEM, H100 GPUs
Core Courses:Distributed Systems, Machine Learning, Advanced AI, Reinforcement Learning, Computer Vision

GOALS: To become a Data Engineer or Cloud Solutions Architect, focused on:

Real-time systems
Serverless architecture
Scalable cloud platforms
Teaching & mentorship in tech

CERTICATIONS
CONTACT
